### ISSUE TITLE
Won't work with tal >= 8.0.0

### ISSUE THREAD

**Issue by joaolsilva** [bbc/talexample#32]
Due to the recent tal requirejs 2.0 migration talexample won't work with tal 8.0.1, and fails with the error "TypeError: undefined is not a function (near '...require.ready...')"

**Comment by rosswilson** [comment]
Hi @joaolsilva, this example application has now been updated to use TAL v8.0.0.

Thanks!
